[phases.setup]
nixPkgs = [
    "python311",
    "postgresql_16", 
    "gcc",
    "pkg-config",
    "libffi",
    "glib",
    # WeasyPrint core dependencies
    "cairo", 
    "pango",
    "gobject-introspection",
    # Additional runtime dependencies
    "shared-mime-info",
    "expat",
    # WeasyPrint runtime dependencies (missing from previous attempts)
    "gdk-pixbuf",
    "libxml2",
    "libxslt", 
    "harfbuzz",
    "fribidi",
    # Additional graphics/font support
    "fontconfig",
    "freetype"
]

# Ensure pip installs happen in build phase for reproducibility
[phases.build]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "pip install -r streamlit-requirements.txt"
]

# Note: glib provides GObject runtime libraries that WeasyPrint needs