"""
Global Disclaimer Generator for All Accounting Standards

This module provides standardized disclaimers for all VeritasLogic.ai generated memos
across ASC 606, ASC 340-40, ASC 842, and future accounting standards.
"""

from datetime import datetime

class DisclaimerGenerator:
    """Generate standardized disclaimers for all accounting memos."""
    
    @staticmethod
    def get_top_banner() -> str:
        """Get the short disclaimer banner for the top of memos."""
        current_date = datetime.now().strftime("%m/%d/%Y")
        
        return f"""<small><em>Disclaimer Version: v1.0 (Effective 08/23/2025)</em></small><br>
<small><em>This memorandum was generated by VeritasLogic.ai using artificial intelligence based solely on information provided by management as of the date of generation. Management is solely responsible for the accuracy and completeness of all inputs and for the accounting judgments, conclusions, and disclosures adopted. The AI may provide incorrect interpretations of nuanced or complex standards, provide incomplete or imprecise citations, rely on outdated guidance, or contain extraction and calculation errors. VeritasLogic.ai makes no representations or warranties and assumes no responsibility for any errors, omissions, or the outcome of any decisions made in reliance on this memorandum. This is not an audit, review, assurance, legal, tax, or valuation opinion and is not intended for third‑party reliance. VeritasLogic.ai employs industry‑standard security controls (e.g., encryption in transit and at rest, role‑based access controls, logging). No system can guarantee absolute security.</em></small>"""
    
    @staticmethod
    def get_full_disclaimer() -> str:
        """Get the full disclaimer for the bottom of memos."""
        
        return """---

<div style="font-size:smaller;">
<br>
<br>
<hr>
<p><em>Disclaimer Version: v1.0 (Effective 08/23/2025)</em></p>

<h6><em>Important Notice and Basis of Preparation</em></h6>
<p><em>This memorandum was generated by VeritasLogic.ai (the "Platform") using artificial intelligence models and retrieval-augmented analysis, based solely on information, documents, and instructions supplied by management as of the generation date (the "Management Information"). The analysis, observations, and citations herein reflect only the Management Information provided and the parameters selected at the time of generation. Any omission, inaccuracy, or subsequent change in facts, circumstances, or regulatory guidance may materially affect the conclusions herein.</em></p>

<h6><em>Management responsibilities</em></h6>
<p><em>Management is solely responsible for:</em></p>
<ul>
<li><em>The accuracy, completeness, and sufficiency of the Management Information and any assumptions provided to the Platform.</em></li>
<li><em>Evaluating the relevance and applicability of the analysis, exercising professional judgment, and determining the appropriate accounting framework, policies, estimates, and disclosures.</em></li>
<li><em>Reaching, documenting, and owning the final accounting conclusions and financial reporting decisions, including communications with the audit committee, external auditors, regulators, and other stakeholders.</em></li>
<li><em>Reviewing and validating all facts, data, calculations, and references contained herein and obtaining necessary consultation from qualified professional advisors.</em></li>
</ul>

<h6><em>Nature and limitations of services</em></h6>
<p><em>The Platform is a technology tool. VeritasLogic.ai is not acting as auditor, reviewer, attester, specialist, or management's expert under PCAOB, AICPA, IAASB, or similar professional standards, and no audit, review, examination, agreed-upon procedures, or other assurance engagement has been performed. Nothing in this memorandum should be construed as an audit opinion, review conclusion, assurance, or comfort letter.</em></p>
<p><em>This memorandum does not constitute legal, tax, regulatory, valuation, investment, or other professional advice and should not be used as a substitute for consultation with qualified advisors or for management's own analysis and judgment.</em></p>
<p><em>References to accounting literature (e.g., U.S. GAAP/ASC, IFRS) and other sources are provided for convenience and may not be exhaustive or current. Interpretations vary, and outcomes depend on specific facts and circumstances.</em></p>

<h6><em>Specific AI limitations</em></h6>
<p><em>The content was generated with the assistance of AI models and may:</em></p>
<ul>
<li><em>Provide incorrect interpretations of nuanced, complex, cross-cutting, or scope-sensitive guidance (e.g., where multiple ASC/IFRS topics interact).</em></li>
<li><em>Provide incomplete, imprecise, or misattributed citations and quotations.</em></li>
<li><em>Reflect guidance or interpretations that are outdated as of the generation date.</em></li>
<li><em>Omit relevant facts when documents are lengthy, poorly scanned, or exceed context limits; OCR and data extraction may misread or truncate content.</em></li>
<li><em>Misapply entity-specific accounting policies, elections, or materiality thresholds unless explicitly provided.</em></li>
<li><em>Produce inconsistent calculations, unit conversions, or roll-forwards if inputs are ambiguous or incomplete.</em></li>
<li><em>Miss embedded features or legal clauses requiring specialized expertise or cross-document synthesis.</em></li>
<li><em>Be sensitive to input phrasing and parameters; small changes in inputs may yield different outputs.</em></li>
</ul>
<p><em>Management must independently verify all facts, calculations, citations, and conclusions before relying on this memorandum.</em></p>

<h6><em>Data security</em></h6>
<p><em>VeritasLogic.ai employs industry-standard security measures designed to protect confidentiality, integrity, and availability, including encryption in transit and at rest, role-based access controls, and logging/monitoring. No system can guarantee absolute security. Data handling and retention are governed by the VeritasLogic.ai Terms of Service and Privacy/Security documentation available at [Security Overview URL] and [Privacy Policy URL]. For security inquiries, contact support@veritaslogic.ai.</em></p>

<h6><em>No duty to update</em></h6>
<p><em>VeritasLogic.ai has no obligation to update this memorandum for subsequent events, new information, changes in facts, or changes in accounting or regulatory guidance after the generation date. If additional information becomes available or assumptions change, management should re-run the analysis and reassess conclusions.</em></p>

<h6><em>Confidentiality and distribution</em></h6>
<p><em>This memorandum is intended solely for internal use by management of [Company Name]. It is not intended for, and should not be relied upon by, any third party. No third-party beneficiaries are created by this memorandum. Distribution to external parties (including lenders, investors, regulators, or auditors) is at management's sole responsibility and risk.</em></p>

<h6><em>Disclaimers of warranties and limitation of liability</em></h6>
<p><em>The memorandum and any related outputs are provided "as is" and "as available," without warranties of any kind, express or implied, including but not limited to accuracy, completeness, timeliness, merchantability, fitness for a particular purpose, or non-infringement.</em></p>
<p><em>To the fullest extent permitted by law, VeritasLogic.ai and its affiliates, licensors, and suppliers disclaim all liability for any losses, damages, penalties, or costs arising from or related to the use of, reliance on, or inability to use this memorandum or the Platform, whether direct, indirect, incidental, consequential, special, exemplary, or punitive. Any liability that cannot be disclaimed is limited as set forth in the VeritasLogic.ai Terms of Service. Nothing herein limits any rights under applicable consumer protection laws.</em></p>
<p><em>In the event of any inconsistency between this disclaimer and the VeritasLogic.ai Terms of Service, the Terms of Service govern.</em></p>

<h6><em>Acceptance</em></h6>
<p><em>By using or relying on this memorandum, management acknowledges and agrees to the foregoing notices, responsibilities, and limitations and confirms that the memorandum will be used only in conjunction with management's own review, professional judgment, and consultation with qualified advisors, as appropriate.</em></p>
</div>"""